spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:log4jdbc:mysql://localhost:3306/data_jpa?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    mode: HTML
    cache: false

